### ISSUE TITLE
运行过程中更可能会出现bug，好像是referer处理的问题，

### ISSUE THREAD

**Issue by YungRun** [nladuo/visit_analytics#1]
panic: runtime error: index out of range

goroutine 227 [running]:
main.GetHostName(0x0, 0x0, 0x0, 0x0)
	H:/Golang/src/github.com/nladuo/visit_analytics/utils.go:22 +0xd9

**Comment by nladuo** [comment]
能打印出strs吗？我在utils.go的18-19行已经对strs的长度进行判断了，说明strs里面至少有一个元素。

**Comment by YungRun** [comment]
// parse hostname from url
func GetHostName(url string) string {
	strs := strings.Split(url, "//")
	if len(strs) < 2 {
		return ""
	}

	host_name := strs[1]

	strs = strings.Split(host_name, "/")
	if len(strs) == 0 {
		return ""
	}
	return strs[0]
}

这个错误偶然发现的，所以我这样改了，我没找到引起错误的refer的特点，所以改这样了，之后没有出错

**Comment by YungRun** [comment]
这个错误偶然发现的，所以我这样改了，我没找到引起错误的refer的特点，所以改这样了，之后没有出错
```
// parse hostname from url
func GetHostName(url string) string {
	strs := strings.Split(url, "//")
	if len(strs) < 2 {
		return ""
	}

	host_name := strs[1]

	strs = strings.Split(host_name, "/")
	if len(strs) == 0 {
		return ""
	}
	return strs[0]
}

```

**Comment by nladuo** [comment]
我刚刚脑子糊涂了。是有问题。因为index是1，所以至少有两个。谢谢啊。
