### ISSUE TITLE
安装包 一直报错

### ISSUE THREAD

**Issue by CL545740896** [nladuo/visit_analytics#2]
..\github.com\andybalholm\cascadia\parser.go:11:2: cannot find package "golang.org/x/net/html" in any of:
        E:\GO\src\golang.org\x\net\html (from $GOROOT)
        E:\GoProject\src\golang.org\x\net\html (from $GOPATH)

**Comment by nladuo** [comment]
golang.org被墙的缘故。可以从第三方网站下载后解压到GOPATH下，https://gopm.io/download
