### ISSUE TITLE
执行安装报错 make prepare

### ISSUE THREAD

**Issue by Blackcatfish** [nladuo/visit_analytics#3]
go get -u gopkg.in/yaml.v2
make: go: Command not found
make: *** [prepare] Error 127

**Comment by nladuo** [comment]
没安装go语言环境

**Comment by Blackcatfish** [comment]
有Java类似功能的吗 有的话发个链接谢谢

**Comment by Blackcatfish** [comment]
go get -u gopkg.in/yaml.v2
package gopkg.in/yaml.v2: cannot download, $GOPATH not set. For more details see: go help gopath
make: *** [prepare] Error 1
安装之后还是不行

**Comment by nladuo** [comment]
自己去看go语言吧。
