### ISSUE TITLE
您好安装报错可以交流下吗

### ISSUE THREAD

**Issue by 0730Nophone** [nladuo/visit_analytics#5]
@

**Comment by nladuo** [comment]
请描述清楚问题。
Duplicate of #6

**Comment by 0730Nophone** [comment]
> 请描述清楚问题。[＃6](https://github.com/nladuo/visit_analytics/issues/6)
> 复制[](https://github.com/nladuo/visit_analytics/issues/6)

**Comment by 0730Nophone** [comment]
我已经成功安装 但是按照给的方法 那段JS是 consle.log（“你的项目地址"）  是否有错误之处。

**Comment by 0730Nophone** [comment]
留个邮箱或者QQ交流下吗？

**Comment by nladuo** [comment]
没有错误，你可以把那个改成什么都可以，console.log删掉也可以。那个js只是一个用于收集Referer请求头的。

**Comment by nladuo** [comment]
代码见：  https://github.com/nladuo/visit_analytics/blob/master/main.go#L36
